### PR TITLE
docs: update readme with docker-compose info

### PR DESCRIPTION
**Pull request by Igogrek**
Signed-off-by: Igogrek <igogrek@gmail.com>

Some basic information on how to run tests and docker-compose for this repo

### CODE REVIEW

**Comment by Igogrek** [comment]
I see that CLA should be signed for this and there's a list of people who already did https://github.com/trustbloc/clabot-config but I could not find any place to sign it. Is it possible?

**Comment by troyronda** [comment]
@igogrek Thanks very much for your contribution. We are working to resolve this issue.

**Comment by troyronda** [comment]
@Igogrek Sorry for the delay. We have updated the [contribution guidelines](https://github.com/trustbloc/community/blob/master/CONTRIBUTING.md#requirements) with CLA instructions.

**Comment by Igogrek** [comment]
@cla-bot check again please?

**Comment by troyronda** [comment]
@cla-bot check again please?

**Comment by troyronda** [comment]
@Igogrek you are all set!

**Pull request merged**
